### ISSUE TITLE
你的链接我点击无效

### ISSUE THREAD

**Issue by Gaohaoyang** [Jack-Q/map-of-sixteen#2]
xjtu校友？

**Comment by Gaohaoyang** [comment]
我猜是你的京东云擎出问题了

**Comment by Jack-Q** [comment]
是XJTU的学长啊！
京东云最近总是出问题，每次都是自动重定向至 "invalid" ，于是就不能访问了。京东云的论坛里也有很多人说有相同的问题，但官方没有处理（看样子已经基本停止了京东云的开发、维护，虽然目前还是测试）。目前正在考虑迁移到其他地方，同时已经在GitHub Pages上临时放置了一份。

**Comment by Gaohaoyang** [comment]
嗯，我在gh-pages上大概看了一下。你都用了什么框架？做的还不错

**Comment by Jack-Q** [comment]
地图使用了Raphaël，此外还用了jQuery。
